{
    _id: "countries" 
    [
    {'Argentina': 'ar'},
    {'Australia': 'au'},
    {'Austria': 'at'},
    {'Azerbaijan': 'az'},
    {'Belgium': 'be'},
    {'Brazil': 'br'},
    {'Bulgaria': 'bg'},
    {'Canada': 'ca'},
    {'Chile': 'cl'},
    {'Colombia': 'co'},
    {'Croatia': 'hr'},
    {'Cyprus': 'cy'},
    {'Czech Republic': 'cz'},
    {'Denmark': 'dk'},
    {'Ecuador': 'ec'},
    {'Estonia': 'ee'},
    {'Finland': 'fi'},
    {'France': 'fr'},
    {'Germany': 'de'},
    {'Greece': 'gr'},
    {'Hong Kong': 'hk'},
    {'Hungary': 'hu'},
    {'Iceland': 'il'},
    {'India': 'in'},
    {'Indonesia': 'id'},
    {'Ireland': 'ie'},
    {'Israel': 'is'},
    {'Italy': 'it'},
    {'Japan': 'jp'},
    {'Latvia': 'lv'},
    {'Lithuania': 'lt'},
    {'Malaysia': 'my'},
    {'Mexico': 'mx'},
    {'Moldova': 'md'},
    {'Netherlands': 'nl'},
    {'New Zealand': 'nz'},
    {'North Macedonia': 'mk'},
    {'Norway': 'no'},
    {'Panama': 'pa'},
    {'Peru': 'pe'},
    {'Philippines': 'ph'},
    {'Poland': 'pl'},
    {'Portugal': 'pt'},
    {'Romania': 'ro'},
    {'Russia': 'ru'},
    {'Serbia': 'rs'},
    {'Singapore': 'sg'},
    {'South Africa': 'za'},
    {'South Korea': 'sk'},
    {'Spain': 'es'},
    {'Sweden': 'se'},
    {'Switzerland': 'ch'},
    {'Thailand': 'th'},
    {'Tunisia': 'tn'},
    {'Turkey': 'tr'},
    {'Ukraine': 'ua'},
    {'United Emirates': 'ae'},
    {'United Kingdom': 'gb'},
    {'United States': 'us'},
    {'Vietnam': 'vn'}
    ]
}