// "data": {
//     "all4": [
//         "gb",
//         "ie"
//     ],
//     "apple": [
//         "ie",
//         "es",
//         "nl",
//         "gb",
//         "pl",
//         "ch",
//         "dk",
//         "se",
//         "no",
//         "it",
//         "md",
//         "in",
//         "cz",
//         "gr",
//         "ua",
//         "ca",
//         "pt",
//         "mx",
//         "ru",
//         "bg",
//         "cy",
//         "fi",
//         "be",
//         "ae",
//         "at",
//         "ee",
//         "th",
//         "de",
//         "az",
//         "fr",
//         "br",
//         "vn",
//         "sg",
//         "us",
//         "jp",
//         "il",
//         "hk",
//         "za",
//         "pa",
//         "au",
//         "ph",
//         "cl",
//         "ar",
//         "nz",
//         "ec",
//         "co",
//         "hu",
//         "id",
//         "kr",
//         "lt",
//         "my",
//         "pe"
//     ],
//     "britbox": [
//         "gb",
//         "us",
//         "ca",
//         "au",
//         "za"
//     ],
//     "crave": [
//         "ca"
//     ],
//     "curiosity": [
//         "gb",
//         "de",
//         "dk",
//         "be",
//         "es",
//         "ch",
//         "cz",
//         "ee",
//         "ro",
//         "rs",
//         "it",
//         "no",
//         "ie",
//         "pt",
//         "pl",
//         "hr",
//         "at",
//         "ru",
//         "us",
//         "tr",
//         "ua",
//         "gr",
//         "bg",
//         "fi",
//         "mk",
//         "th",
//         "nl",
//         "cy",
//         "ca",
//         "fr",
//         "il",
//         "is",
//         "hk",
//         "vn",
//         "jp",
//         "az",
//         "mx",
//         "in",
//         "nz",
//         "ae",
//         "za",
//         "br",
//         "se",
//         "au",
//         "ph",
//         "cl",
//         "pa",
//         "ar",
//         "sg",
//         "ec",
//         "co",
//         "hu",
//         "id",
//         "kr",
//         "lt",
//         "my",
//         "pe"
//     ],
//     "disney": [
//         "ca",
//         "gb",
//         "us",
//         "nl",
//         "au",
//         "nz",
//         "at",
//         "de",
//         "it",
//         "es",
//         "ch",
//         "fr",
//         "be",
//         "dk",
//         "fi",
//         "no",
//         "pt",
//         "se",
//         "ar",
//         "br",
//         "cl",
//         "co",
//         "mx",
//         "ie",
//         "jp",
//         "id",
//         "is",
//         "ec",
//         "pa",
//         "pe",
//         "sg",
//         "my",
//         "th",
//         "kr",
//         "hk",
//         "za",
//         "tr"
//     ],
//     "hbo": [
//         "nl",
//         "us",
//         "ar",
//         "br",
//         "cl",
//         "co",
//         "ec",
//         "mx",
//         "pe",
//         "dk",
//         "fi",
//         "no",
//         "es",
//         "se",
//         "bg",
//         "hr",
//         "cz",
//         "hu",
//         "md",
//         "mk",
//         "pl",
//         "pt",
//         "ro",
//         "rs"
//     ],
//     "hotstar": [
//         "in",
//         "ca",
//         "gb",
//         "id",
//         "sg"
//     ],
//     "hulu": [
//         "us"
//     ],
//     "iplayer": [
//         "gb"
//     ],
//     "mubi": [
//         "ch",
//         "il",
//         "ru",
//         "be",
//         "es",
//         "at",
//         "mk",
//         "pl",
//         "md",
//         "ua",
//         "rs",
//         "se",
//         "jp",
//         "ee",
//         "ca",
//         "cy",
//         "ro",
//         "bg",
//         "dk",
//         "fi",
//         "nl",
//         "fr",
//         "az",
//         "gb",
//         "no",
//         "gr",
//         "de",
//         "hk",
//         "us",
//         "it",
//         "ae",
//         "sg",
//         "ie",
//         "vn",
//         "pa",
//         "za",
//         "cl",
//         "au",
//         "nz",
//         "tr",
//         "ar",
//         "th",
//         "in",
//         "br",
//         "ph",
//         "mx",
//         "hr",
//         "ec",
//         "co",
//         "hu",
//         "id",
//         "kr",
//         "lt",
//         "my",
//         "pe"
//     ],
//     "netflix": [
//         "ar",
//         "at",
//         "au",
//         "be",
//         "br",
//         "ca",
//         "ch",
//         "cl",
//         "co",
//         "cz",
//         "de",
//         "dk",
//         "ec",
//         "ee",
//         "es",
//         "fi",
//         "fr",
//         "gb",
//         "gr",
//         "hu",
//         "id",
//         "ie",
//         "in",
//         "it",
//         "jp",
//         "kr",
//         "lt",
//         "mx",
//         "my",
//         "nl",
//         "no",
//         "nz",
//         "pe",
//         "ph",
//         "pl",
//         "pt",
//         "ro",
//         "se",
//         "sg",
//         "th",
//         "tr",
//         "us",
//         "za",
//         "hr",
//         "az",
//         "bg",
//         "cy",
//         "hk",
//         "is",
//         "il",
//         "md",
//         "mk",
//         "rs",
//         "ua",
//         "ae",
//         "vn",
//         "pa"
//     ],
//     "now": [
//         "gb",
//         "ie",
//         "it"
//     ],
//     "paramount": [
//         "us"
//     ],
//     "peacock": [
//         "us"
//     ],
//     "prime": [
//         "jp",
//         "nl",
//         "nz",
//         "se",
//         "il",
//         "dk",
//         "th",
//         "ec",
//         "cl",
//         "ee",
//         "cz",
//         "de",
//         "no",
//         "ru",
//         "md",
//         "ph",
//         "co",
//         "rs",
//         "id",
//         "pe",
//         "za",
//         "fr",
//         "in",
//         "hk",
//         "pa",
//         "kr",
//         "ro",
//         "hr",
//         "at",
//         "ca",
//         "ar",
//         "ie",
//         "us",
//         "hu",
//         "br",
//         "it",
//         "mx",
//         "pl",
//         "sg",
//         "ch",
//         "cy",
//         "lt",
//         "my",
//         "is",
//         "es",
//         "ae",
//         "az",
//         "bg",
//         "pt",
//         "au",
//         "fi",
//         "tr",
//         "be",
//         "gr",
//         "gb",
//         "ua",
//         "mk",
//         "vn"
//     ],
//     "showtime": [
//         "us"
//     ],
//     "stan": [
//         "au"
//     ],
//     "starz": [
//         "us"
//     ],
//     "zee5": [
//         "gb",
//         "de",
//         "dk",
//         "be",
//         "es",
//         "ch",
//         "cz",
//         "ee",
//         "ro",
//         "rs",
//         "it",
//         "no",
//         "ie",
//         "pt",
//         "pl",
//         "hr",
//         "at",
//         "ru",
//         "us",
//         "tr",
//         "ua",
//         "gr",
//         "bg",
//         "fi",
//         "mk",
//         "th",
//         "nl",
//         "cy",
//         "md",
//         "ca",
//         "fr",
//         "il",
//         "is",
//         "hk",
//         "vn",
//         "jp",
//         "az",
//         "mx",
//         "in",
//         "nz",
//         "ae",
//         "za",
//         "br",
//         "se",
//         "au",
//         "ph",
//         "cl",
//         "pa",
//         "ar",
//         "sg",
//         "ec",
//         "co",
//         "hu",
//         "id",
//         "kr",
//         "lt",
//         "my",
//         "pe"
//     ]
// }



// {
//     imdbID: 'tt3398228',
//     tmdbID: '61222',
//     imdbRating: 88,
//     imdbVoteCount: 151937,
//     tmdbRating: 85,
//     backdropPath: '/y64WatnpvoeudfapTPx9QFVKbqM.jpg',
//     backdropURLs: [Object],
//     originalTitle: 'BoJack Horseman',
//     genres: [Array],
//     countries: [Array],
//     year: 2014,
//     firstAirYear: 2014,
//     lastAirYear: 2020,
//     episodeRuntimes: [Array],
//     cast: [Array],
//     significants: [Array],
//     title: 'BoJack Horseman',
//     overview: `Meet the most beloved sitcom horse of the 90s - 20 years later. BoJack Horseman was the star of the hit TV show "Horsin' Around," but today he's washed up, living in Hollywood, complaining about everything, and wearing colorful sweaters.`,
//     video: 'i1eJMig5Ik4',
//     posterPath: '/pB9L0jAnEQLMKgexqCEocEW8TA.jpg',
//     posterURLs: [Object],
//     seasons: 6,
//     episodes: 76,
//     age: 15,
//     status: 4,
//     tagline: '',
//     streamingInfo: [Object],
//     originalLanguage: 'en'
//   }


// {
// 	"status": 200,
// 	"message": "shows found",
// 	"data": {
		// "results": [
			// {
			// 	"imdbID": "tt3398228",
			// 	"tmdbID": "61222",
			// 	"imdbRating": 88,
			// 	"imdbVoteCount": 151937,
			// 	"tmdbRating": 85,
			// 	"backdropPath": "/y64WatnpvoeudfapTPx9QFVKbqM.jpg",
			// 	"backdropURLs": {
			// 		"300": "https://image.tmdb.org/t/p/w300/y64WatnpvoeudfapTPx9QFVKbqM.jpg",
			// 		"780": "https://image.tmdb.org/t/p/w780/y64WatnpvoeudfapTPx9QFVKbqM.jpg",
			// 		"1280": "https://image.tmdb.org/t/p/w1280/y64WatnpvoeudfapTPx9QFVKbqM.jpg",
			// 		"original": "https://image.tmdb.org/t/p/original/y64WatnpvoeudfapTPx9QFVKbqM.jpg"
			// 	},
			// 	"originalTitle": "BoJack Horseman",
			// 	"genres": [
			// 		16,
			// 		35,
			// 		18
			// 	],
			// 	"countries": [
			// 		"US"
			// 	],
			// 	"year": 2014,
			// 	"firstAirYear": 2014,
			// 	"lastAirYear": 2020,
			// 	"episodeRuntimes": [
			// 		25
			// 	],
			// 	"cast": [
			// 		"Will Arnett",
			// 		"Aaron Paul",
			// 		"Alison Brie",
			// 		"Amy Sedaris",
			// 		"Paul F. Tompkins",
			// 		"Adam Conover",
			// 		"Keith Olbermann"
			// 	],
			// 	"significants": [
			// 		"Raphael Bob-Waksberg"
			// 	],
			// 	"title": "BoJack Horseman",
			// 	"overview": "Meet the most beloved sitcom horse of the 90s - 20 years later. BoJack Horseman was the star of the hit TV show \"Horsin' Around,\" but today he's washed up, living in Hollywood, complaining about everything, and wearing colorful sweaters.",
			// 	"video": "i1eJMig5Ik4",
			// 	"posterPath": "/pB9L0jAnEQLMKgexqCEocEW8TA.jpg",
			// 	"posterURLs": {
			// 		"92": "https://image.tmdb.org/t/p/w92/pB9L0jAnEQLMKgexqCEocEW8TA.jpg",
			// 		"154": "https://image.tmdb.org/t/p/w154/pB9L0jAnEQLMKgexqCEocEW8TA.jpg",
			// 		"185": "https://image.tmdb.org/t/p/w185/pB9L0jAnEQLMKgexqCEocEW8TA.jpg",
			// 		"342": "https://image.tmdb.org/t/p/w342/pB9L0jAnEQLMKgexqCEocEW8TA.jpg",
			// 		"500": "https://image.tmdb.org/t/p/w500/pB9L0jAnEQLMKgexqCEocEW8TA.jpg",
			// 		"780": "https://image.tmdb.org/t/p/w780/pB9L0jAnEQLMKgexqCEocEW8TA.jpg",
			// 		"original": "https://image.tmdb.org/t/p/original/pB9L0jAnEQLMKgexqCEocEW8TA.jpg"
			// 	},
			// 	"seasons": 6,
			// 	"episodes": 76,
			// 	"age": 15,
			// 	"status": 4,
			// 	"tagline": "",
			// 	"streamingInfo": {
			// 		"netflix": {
			// 			"ca": {
			// 				"link": "https://www.netflix.com/title/70300800/",
			// 				"added": 1600283847,
			// 				"leaving": 0
			// 			}
			// 		}
			// 	},
			// 	"originalLanguage": "en"
			// }
		// ],
		// "total_pages": 1
// 	}
// }


{
    Id: "email"
    IsSetUp: true
    Location: "ca"
    Subscriptions: ["netflix", "disney"]
    shows: [			{
        "imdbID": "tt3398228",
        "tmdbID": "61222",
        "imdbRating": 88,
        "imdbVoteCount": 151937,
        "tmdbRating": 85,
        "backdropPath": "/y64WatnpvoeudfapTPx9QFVKbqM.jpg",
        "backdropURLs": {
            "300": "https://image.tmdb.org/t/p/w300/y64WatnpvoeudfapTPx9QFVKbqM.jpg",
            "780": "https://image.tmdb.org/t/p/w780/y64WatnpvoeudfapTPx9QFVKbqM.jpg",
            "1280": "https://image.tmdb.org/t/p/w1280/y64WatnpvoeudfapTPx9QFVKbqM.jpg",
            "original": "https://image.tmdb.org/t/p/original/y64WatnpvoeudfapTPx9QFVKbqM.jpg"
        },
        "originalTitle": "BoJack Horseman",
        "genres": [
            16,
            35,
            18
        ],
        "countries": [
            "US"
        ],
        "year": 2014,
        "firstAirYear": 2014,
        "lastAirYear": 2020,
        "episodeRuntimes": [
            25
        ],
        "cast": [
            "Will Arnett",
            "Aaron Paul",
            "Alison Brie",
            "Amy Sedaris",
            "Paul F. Tompkins",
            "Adam Conover",
            "Keith Olbermann"
        ],
        "significants": [
            "Raphael Bob-Waksberg"
        ],
        "title": "BoJack Horseman",
        "overview": "Meet the most beloved sitcom horse of the 90s - 20 years later. BoJack Horseman was the star of the hit TV show \"Horsin' Around,\" but today he's washed up, living in Hollywood, complaining about everything, and wearing colorful sweaters.",
        "video": "i1eJMig5Ik4",
        "posterPath": "/pB9L0jAnEQLMKgexqCEocEW8TA.jpg",
        "posterURLs": {
            "92": "https://image.tmdb.org/t/p/w92/pB9L0jAnEQLMKgexqCEocEW8TA.jpg",
            "154": "https://image.tmdb.org/t/p/w154/pB9L0jAnEQLMKgexqCEocEW8TA.jpg",
            "185": "https://image.tmdb.org/t/p/w185/pB9L0jAnEQLMKgexqCEocEW8TA.jpg",
            "342": "https://image.tmdb.org/t/p/w342/pB9L0jAnEQLMKgexqCEocEW8TA.jpg",
            "500": "https://image.tmdb.org/t/p/w500/pB9L0jAnEQLMKgexqCEocEW8TA.jpg",
            "780": "https://image.tmdb.org/t/p/w780/pB9L0jAnEQLMKgexqCEocEW8TA.jpg",
            "original": "https://image.tmdb.org/t/p/original/pB9L0jAnEQLMKgexqCEocEW8TA.jpg"
        },
        "seasons": 6,
        "episodes": 76,
        "age": 15,
        "status": 4,
        "tagline": "",
        "streamingInfo": {
            "netflix": {
                "ca": {
                    "link": "https://www.netflix.com/title/70300800/",
                    "added": 1600283847,
                    "leaving": 0
                }
            }
        },
        "originalLanguage": "en"
    }]
}