results: [
    {
      imdbID: 'tt15407098',
      tmdbID: '157282',
      imdbRating: 70,
      imdbVoteCount: 1566,
      tmdbRating: 70,
      backdropPath: '/o15mg5xbGkSPfW4e8ES42WzpZAy.jpg',
      backdropURLs: [Object],
      originalTitle: 'Sister Boniface Mysteries',
      genres: [Array],
      countries: [Array],
      year: 2022,
      firstAirYear: 2022,
      lastAirYear: 2022,
      episodeRuntimes: [Array],
      cast: [Array],
      significants: [Array],
      title: 'Sister Boniface Mysteries',
      overview: "First there was Father Brown. Now, say hello to Sister Boniface. This clever, moped-riding nun is the police's secret weapon for solving murders in this divine Father Brown spin-off.",     
      video: '8cIerKb_I8c',
      posterPath: '/leaPXZKi7OBKfLUwyoGu5bP5WU2.jpg',
      posterURLs: [Object],
      seasons: 1,
      episodes: 10,
      age: 11,
      status: 1,
      tagline: '',
      streamingInfo: [Object],
      originalLanguage: 'en'
    }
  ],
  total_pages: 1
}
GET /show?country=au&service=britbox&type=series&keyword=hello&page=1&output_language=en&language=en 304 - - 224.856 ms
{
  country: 'ca',
  service: 'crave',
  type: 'series',
  keyword: 'station',
  page: '1',
  output_language: 'en',
  language: 'en'
}
{
  country: 'au',
  service: 'britbox',
  type: 'series',
  keyword: 'hello',
  page: '1',
  output_language: 'en',
  language: 'en'
}
{
  results: [
    {
      imdbID: 'tt0397138',
      tmdbID: '429',
      imdbRating: 83,
      imdbVoteCount: 7434,
      tmdbRating: 81,
      backdropPath: '/uFyPlkJphA4MUIwjB1GE3wUH8SE.jpg',
      backdropURLs: [Object],
      originalTitle: 'Corner Gas',
      genres: [Array],
      countries: [Array],
      year: 2004,
      firstAirYear: 2004,
      lastAirYear: 2009,
      episodeRuntimes: [Array],
      cast: [Array],
      significants: [Array],
      title: 'Corner Gas',
      overview: 'Following the adventures of a bunch of nobodies who get up to a whole lot of nothing in the fictional prairie town of Dog River, Saskatchewan, Corner Gas focuses on the life (or lack thereof) of Brent LeRoy, proprietor of a gas station that is the only stop for miles around and a hub of action on the Prairies.',
      video: '',
      posterPath: '/2auwYcyedZ9GwrwRcVMijIPMO0T.jpg',
      posterURLs: [Object],
      seasons: 6,
      episodes: 108,
      age: 6,
      status: 4,
      tagline: '',
      streamingInfo: [Object],
      originalLanguage: 'en'
    },
    {
      imdbID: 'tt14903810',
      tmdbID: '128966',
      imdbRating: 66,
      imdbVoteCount: 259,
      tmdbRating: 65,
      backdropPath: '/eQqmPz78gt69MutwBAQTJbuRLms.jpg',
      backdropURLs: [Object],
      originalTitle: 'Small Town News: KPVM Pahrump',
      genres: [Array],
      countries: [Array],
      year: 2021,
      firstAirYear: 2021,
      lastAirYear: 2021,
      episodeRuntimes: [Array],
      cast: [Array],
      significants: [],
      title: 'Small Town News: KPVM Pahrump',
      overview: 'Pulling back the curtain on life at a privately owned TV station in the small desert town of Pahrump, Nevada, revealing a colorful cast of characters in front of and behind the cameras.',  
      video: 'sfu30G4AkJA',
      posterPath: '/zTRkIOK0x15WA9zeaxyKBwEZPM3.jpg',
      posterURLs: [Object],
      seasons: 1,
      episodes: 6,
      age: 13,
      status: 4,
      tagline: '',
      streamingInfo: [Object],
      originalLanguage: 'en'
    },
    {
      imdbID: 'tt0106145',
      tmdbID: '580',
      imdbRating: 81,
      imdbVoteCount: 62757,
      tmdbRating: 78,
      backdropPath: '/jB3Ksk1tvhksdTa0xvI7l4LFHsy.jpg',
      backdropURLs: [Object],
      originalTitle: 'Star Trek: Deep Space Nine',
      genres: [Array],
      countries: [Array],
      year: 1993,
      firstAirYear: 1993,
      lastAirYear: 1999,
      episodeRuntimes: [Array],
      cast: [Array],
      significants: [Array],
      title: 'Star Trek: Deep Space Nine',
      overview: 'At Deep Space Nine, a space station located next to a wormhole in the vicinity of the liberated planet of Bajor, Commander Sisko and crew welcome alien visitors, root out evildoers and solve all types of unexpected problems that come their way.',
      video: 'cwNFUgYWGG4',
      posterPath: '/37gPCTyiQOLa9vJeKrpX4HqRq6P.jpg',
      posterURLs: [Object],
      seasons: 7,
      episodes: 176,
      age: 11,
      status: 4,
      tagline: '',
      streamingInfo: [Object],
      originalLanguage: 'en'
    },
    {
      imdbID: 'tt10574236',
      tmdbID: '90972',
      imdbRating: 76,
      imdbVoteCount: 24754,
      tmdbRating: 69,
      backdropPath: '/kiiPOuzjyIe793tgGsM5j5DaRxb.jpg',
      backdropURLs: [Object],
      originalTitle: 'Station Eleven',
      genres: [Array],
      countries: [Array],
      year: 2021,
      firstAirYear: 2021,
      lastAirYear: 2022,
      episodeRuntimes: [Array],
      cast: [Array],
      significants: [Array],
      title: 'Station Eleven',
      overview: "A post apocalyptic saga spanning multiple timelines telling the stories of survivors of a devastating flu as they attempt to rebuild and reimagine the world anew while holding on to the best of what's been lost.",
      video: 'LPm52rq8CZA',
      posterPath: '/xWlhMOzRxUpu4uzkWcDQOaESCE.jpg',
      posterURLs: [Object],
      seasons: 1,
      episodes: 10,
      age: 17,
      status: 4,
      tagline: '',
      streamingInfo: [Object],
      originalLanguage: 'en'
    }
  ],
  total_pages: 1
}
GET /show?country=ca&service=crave&type=series&keyword=station&page=1&output_language=en&language=en 200 7615 - 218.342 ms
{
  results: [
    {
      imdbID: 'tt15407098',
      tmdbID: '157282',
      imdbRating: 70,
      imdbVoteCount: 1566,
      tmdbRating: 70,
      backdropPath: '/o15mg5xbGkSPfW4e8ES42WzpZAy.jpg',
      backdropURLs: [Object],
      originalTitle: 'Sister Boniface Mysteries',
      genres: [Array],
      countries: [Array],
      year: 2022,
      firstAirYear: 2022,
      lastAirYear: 2022,
      episodeRuntimes: [Array],
      cast: [Array],
      significants: [Array],
      title: 'Sister Boniface Mysteries',
      overview: "First there was Father Brown. Now, say hello to Sister Boniface. This clever, moped-riding nun is the police's secret weapon for solving murders in this divine Father Brown spin-off.",     
      video: '8cIerKb_I8c',
      posterPath: '/leaPXZKi7OBKfLUwyoGu5bP5WU2.jpg',
      posterURLs: [Object],
      seasons: 1,
      episodes: 10,
      age: 11,
      status: 1,
      tagline: '',
      streamingInfo: [Object],
      originalLanguage: 'en'
    }
  ],
  total_pages: 1
}
GET /show?country=au&service=britbox&type=series&keyword=hello&page=1&output_language=en&language=en 304 - - 232.623 ms
{
  country: 'ca',
  service: 'crave',
  type: 'series',
  keyword: 'station',
  page: '1',
  output_language: 'en',
  language: 'en'
}
{
  country: 'au',
  service: 'britbox',
  type: 'series',
  keyword: 'hello',
  page: '1',
  output_language: 'en',
  language: 'en'
}
{
  results: [
    {
      imdbID: 'tt0397138',
      tmdbID: '429',
      imdbRating: 83,
      imdbVoteCount: 7434,
      tmdbRating: 81,
      backdropPath: '/uFyPlkJphA4MUIwjB1GE3wUH8SE.jpg',
      backdropURLs: [Object],
      originalTitle: 'Corner Gas',
      genres: [Array],
      countries: [Array],
      year: 2004,
      firstAirYear: 2004,
      lastAirYear: 2009,
      episodeRuntimes: [Array],
      cast: [Array],
      significants: [Array],
      title: 'Corner Gas',
      overview: 'Following the adventures of a bunch of nobodies who get up to a whole lot of nothing in the fictional prairie town of Dog River, Saskatchewan, Corner Gas focuses on the life (or lack thereof) of Brent LeRoy, proprietor of a gas station that is the only stop for miles around and a hub of action on the Prairies.',
      video: '',
      posterPath: '/2auwYcyedZ9GwrwRcVMijIPMO0T.jpg',
      posterURLs: [Object],
      seasons: 6,
      episodes: 108,
      age: 6,
      status: 4,
      tagline: '',
      streamingInfo: [Object],
      originalLanguage: 'en'
    },
    {
      imdbID: 'tt14903810',
      tmdbID: '128966',
      imdbRating: 66,
      imdbVoteCount: 259,
      tmdbRating: 65,
      backdropPath: '/eQqmPz78gt69MutwBAQTJbuRLms.jpg',
      backdropURLs: [Object],
      originalTitle: 'Small Town News: KPVM Pahrump',
      genres: [Array],
      countries: [Array],
      year: 2021,
      firstAirYear: 2021,
      lastAirYear: 2021,
      episodeRuntimes: [Array],
      cast: [Array],
      significants: [],
      title: 'Small Town News: KPVM Pahrump',
      overview: 'Pulling back the curtain on life at a privately owned TV station in the small desert town of Pahrump, Nevada, revealing a colorful cast of characters in front of and behind the cameras.',  
      video: 'sfu30G4AkJA',
      posterPath: '/zTRkIOK0x15WA9zeaxyKBwEZPM3.jpg',
      posterURLs: [Object],
      seasons: 1,
      episodes: 6,
      age: 13,
      status: 4,
      tagline: '',
      streamingInfo: [Object],
      originalLanguage: 'en'
    },
    {
      imdbID: 'tt0106145',
      tmdbID: '580',
      imdbRating: 81,
      imdbVoteCount: 62757,
      tmdbRating: 78,
      backdropPath: '/jB3Ksk1tvhksdTa0xvI7l4LFHsy.jpg',
      backdropURLs: [Object],
      originalTitle: 'Star Trek: Deep Space Nine',
      genres: [Array],
      countries: [Array],
      year: 1993,
      firstAirYear: 1993,
      lastAirYear: 1999,
      episodeRuntimes: [Array],
      cast: [Array],
      significants: [Array],
      title: 'Star Trek: Deep Space Nine',
      overview: 'At Deep Space Nine, a space station located next to a wormhole in the vicinity of the liberated planet of Bajor, Commander Sisko and crew welcome alien visitors, root out evildoers and solve all types of unexpected problems that come their way.',
      video: 'cwNFUgYWGG4',
      posterPath: '/37gPCTyiQOLa9vJeKrpX4HqRq6P.jpg',
      posterURLs: [Object],
      seasons: 7,
      episodes: 176,
      age: 11,
      status: 4,
      tagline: '',
      streamingInfo: [Object],
      originalLanguage: 'en'
    },
    {
      imdbID: 'tt10574236',
      tmdbID: '90972',
      imdbRating: 76,
      imdbVoteCount: 24754,
      tmdbRating: 69,
      backdropPath: '/kiiPOuzjyIe793tgGsM5j5DaRxb.jpg',
      backdropURLs: [Object],
      originalTitle: 'Station Eleven',
      genres: [Array],
      countries: [Array],
      year: 2021,
      firstAirYear: 2021,
      lastAirYear: 2022,
      episodeRuntimes: [Array],
      cast: [Array],
      significants: [Array],
      title: 'Station Eleven',
      overview: "A post apocalyptic saga spanning multiple timelines telling the stories of survivors of a devastating flu as they attempt to rebuild and reimagine the world anew while holding on to the best of what's been lost.",
      video: 'LPm52rq8CZA',
      posterPath: '/xWlhMOzRxUpu4uzkWcDQOaESCE.jpg',
      posterURLs: [Object],
      seasons: 1,
      episodes: 10,
      age: 17,
      status: 4,
      tagline: '',
      streamingInfo: [Object],
      originalLanguage: 'en'
    }
  ],
  total_pages: 1
}
GET /show?country=ca&service=crave&type=series&keyword=station&page=1&output_language=en&language=en 304 - - 268.462 ms
{
  results: [
    {
      imdbID: 'tt15407098',
      tmdbID: '157282',
      imdbRating: 70,
      imdbVoteCount: 1566,
      tmdbRating: 70,
      backdropPath: '/o15mg5xbGkSPfW4e8ES42WzpZAy.jpg',
      backdropURLs: [Object],
      originalTitle: 'Sister Boniface Mysteries',
      genres: [Array],
      countries: [Array],
      year: 2022,
      firstAirYear: 2022,
      lastAirYear: 2022,
      episodeRuntimes: [Array],
      cast: [Array],
      significants: [Array],
      title: 'Sister Boniface Mysteries',
      overview: "First there was Father Brown. Now, say hello to Sister Boniface. This clever, moped-riding nun is the police's secret weapon for solving murders in this divine Father Brown spin-off.",     
      video: '8cIerKb_I8c',
      posterPath: '/leaPXZKi7OBKfLUwyoGu5bP5WU2.jpg',
      posterURLs: [Object],
      seasons: 1,
      episodes: 10,
      age: 11,
      status: 1,
      tagline: '',
      streamingInfo: [Object],
      originalLanguage: 'en'
    }
  ],
  total_pages: 1
}
GET /show?country=au&service=britbox&type=series&keyword=hello&page=1&output_language=en&language=en 304 - - 220.790 ms
{
  country: 'ca',
  service: 'crave',
  type: 'series',
  keyword: 'station',
  page: '1',
  output_language: 'en',
  language: 'en'
}
{
  country: 'au',
  service: 'britbox',
  type: 'series',
  keyword: 'hello',
  page: '1',
  output_language: 'en',
  language: 'en'
}
{
  results: [
    {
      imdbID: 'tt15407098',
      tmdbID: '157282',
      imdbRating: 70,
      imdbVoteCount: 1566,
      tmdbRating: 70,
      backdropPath: '/o15mg5xbGkSPfW4e8ES42WzpZAy.jpg',
      backdropURLs: [Object],
      originalTitle: 'Sister Boniface Mysteries',
      genres: [Array],
      countries: [Array],
      year: 2022,
      firstAirYear: 2022,
      lastAirYear: 2022,
      episodeRuntimes: [Array],
      cast: [Array],
      significants: [Array],
      title: 'Sister Boniface Mysteries',
      overview: "First there was Father Brown. Now, say hello to Sister Boniface. This clever, moped-riding nun is the police's secret weapon for solving murders in this divine Father Brown spin-off.",     
      video: '8cIerKb_I8c',
      posterPath: '/leaPXZKi7OBKfLUwyoGu5bP5WU2.jpg',
      posterURLs: [Object],
      seasons: 1,
      episodes: 10,
      age: 11,
      status: 1,
      tagline: '',
      streamingInfo: [Object],
      originalLanguage: 'en'
    }
  ],
  total_pages: 1
}
GET /show?country=au&service=britbox&type=series&keyword=hello&page=1&output_language=en&language=en 304 - - 204.515 ms
{
  results: [
    {
      imdbID: 'tt0397138',
      tmdbID: '429',
      imdbRating: 83,
      imdbVoteCount: 7434,
      tmdbRating: 81,
      backdropPath: '/uFyPlkJphA4MUIwjB1GE3wUH8SE.jpg',
      backdropURLs: [Object],
      originalTitle: 'Corner Gas',
      genres: [Array],
      countries: [Array],
      year: 2004,
      firstAirYear: 2004,
      lastAirYear: 2009,
      episodeRuntimes: [Array],
      cast: [Array],
      significants: [Array],
      title: 'Corner Gas',
      overview: 'Following the adventures of a bunch of nobodies who get up to a whole lot of nothing in the fictional prairie town of Dog River, Saskatchewan, Corner Gas focuses on the life (or lack thereof) of Brent LeRoy, proprietor of a gas station that is the only stop for miles around and a hub of action on the Prairies.',
      video: '',
      posterPath: '/2auwYcyedZ9GwrwRcVMijIPMO0T.jpg',
      posterURLs: [Object],
      seasons: 6,
      episodes: 108,
      age: 6,
      status: 4,
      tagline: '',
      streamingInfo: [Object],
      originalLanguage: 'en'
    },
    {
      imdbID: 'tt14903810',
      tmdbID: '128966',
      imdbRating: 66,
      imdbVoteCount: 259,
      tmdbRating: 65,
      backdropPath: '/eQqmPz78gt69MutwBAQTJbuRLms.jpg',
      backdropURLs: [Object],
      originalTitle: 'Small Town News: KPVM Pahrump',
      genres: [Array],
      countries: [Array],
      year: 2021,
      firstAirYear: 2021,
      lastAirYear: 2021,
      episodeRuntimes: [Array],
      cast: [Array],
      significants: [],
      title: 'Small Town News: KPVM Pahrump',
      overview: 'Pulling back the curtain on life at a privately owned TV station in the small desert town of Pahrump, Nevada, revealing a colorful cast of characters in front of and behind the cameras.',  
      video: 'sfu30G4AkJA',
      posterPath: '/zTRkIOK0x15WA9zeaxyKBwEZPM3.jpg',
      posterURLs: [Object],
      seasons: 1,
      episodes: 6,
      age: 13,
      status: 4,
      tagline: '',
      streamingInfo: [Object],
      originalLanguage: 'en'
    },
    {
      imdbID: 'tt0106145',
      tmdbID: '580',
      imdbRating: 81,
      imdbVoteCount: 62757,
      tmdbRating: 78,
      backdropPath: '/jB3Ksk1tvhksdTa0xvI7l4LFHsy.jpg',
      backdropURLs: [Object],
      originalTitle: 'Star Trek: Deep Space Nine',
      genres: [Array],
      countries: [Array],
      year: 1993,
      firstAirYear: 1993,
      lastAirYear: 1999,
      episodeRuntimes: [Array],
      cast: [Array],
      significants: [Array],
      title: 'Star Trek: Deep Space Nine',
      overview: 'At Deep Space Nine, a space station located next to a wormhole in the vicinity of the liberated planet of Bajor, Commander Sisko and crew welcome alien visitors, root out evildoers and solve all types of unexpected problems that come their way.',
      video: 'cwNFUgYWGG4',
      posterPath: '/37gPCTyiQOLa9vJeKrpX4HqRq6P.jpg',
      posterURLs: [Object],
      seasons: 7,
      episodes: 176,
      age: 11,
      status: 4,
      tagline: '',
      streamingInfo: [Object],
      originalLanguage: 'en'
    },
    {
      imdbID: 'tt10574236',
      tmdbID: '90972',
      imdbRating: 76,
      imdbVoteCount: 24754,
      tmdbRating: 69,
      backdropPath: '/kiiPOuzjyIe793tgGsM5j5DaRxb.jpg',
      backdropURLs: [Object],
      originalTitle: 'Station Eleven',
      genres: [Array],
      countries: [Array],
      year: 2021,
      firstAirYear: 2021,
      lastAirYear: 2022,
      episodeRuntimes: [Array],
      cast: [Array],
      significants: [Array],
      title: 'Station Eleven',
      overview: "A post apocalyptic saga spanning multiple timelines telling the stories of survivors of a devastating flu as they attempt to rebuild and reimagine the world anew while holding on to the best of what's been lost.",
      video: 'LPm52rq8CZA',
      posterPath: '/xWlhMOzRxUpu4uzkWcDQOaESCE.jpg',
      posterURLs: [Object],
      seasons: 1,
      episodes: 10,
      age: 17,
      status: 4,
      tagline: '',
      streamingInfo: [Object],
      originalLanguage: 'en'
    }
  ],
  total_pages: 1
}
GET /show?country=ca&service=crave&type=series&keyword=station&page=1&output_language=en&language=en 304 - - 217.372 ms
{
  country: 'ca',
  service: 'crave',
  type: 'series',
  keyword: 'station',
  page: '1',
  output_language: 'en',
  language: 'en'
}
{
  country: 'au',
  service: 'britbox',
  type: 'series',
  keyword: 'hello',
  page: '1',
  output_language: 'en',
  language: 'en'
}
{
  results: [
    {
      imdbID: 'tt0397138',
      tmdbID: '429',
      imdbRating: 83,
      imdbVoteCount: 7434,
      tmdbRating: 81,
      backdropPath: '/uFyPlkJphA4MUIwjB1GE3wUH8SE.jpg',
      backdropURLs: [Object],
      originalTitle: 'Corner Gas',
      genres: [Array],
      countries: [Array],
      year: 2004,
      firstAirYear: 2004,
      lastAirYear: 2009,
      episodeRuntimes: [Array],
      cast: [Array],
      significants: [Array],
      title: 'Corner Gas',
      overview: 'Following the adventures of a bunch of nobodies who get up to a whole lot of nothing in the fictional prairie town of Dog River, Saskatchewan, Corner Gas focuses on the life (or lack thereof) of Brent LeRoy, proprietor of a gas station that is the only stop for miles around and a hub of action on the Prairies.',
      video: '',
      posterPath: '/2auwYcyedZ9GwrwRcVMijIPMO0T.jpg',
      posterURLs: [Object],
      seasons: 6,
      episodes: 108,
      age: 6,
      status: 4,
      tagline: '',
      streamingInfo: [Object],
      originalLanguage: 'en'
    },
    {
      imdbID: 'tt14903810',
      tmdbID: '128966',
      imdbRating: 66,
      imdbVoteCount: 259,
      tmdbRating: 65,
      backdropPath: '/eQqmPz78gt69MutwBAQTJbuRLms.jpg',
      backdropURLs: [Object],
      originalTitle: 'Small Town News: KPVM Pahrump',
      genres: [Array],
      countries: [Array],
      year: 2021,
      firstAirYear: 2021,
      lastAirYear: 2021,
      episodeRuntimes: [Array],
      cast: [Array],
      significants: [],
      title: 'Small Town News: KPVM Pahrump',
      overview: 'Pulling back the curtain on life at a privately owned TV station in the small desert town of Pahrump, Nevada, revealing a colorful cast of characters in front of and behind the cameras.',  
      video: 'sfu30G4AkJA',
      posterPath: '/zTRkIOK0x15WA9zeaxyKBwEZPM3.jpg',
      posterURLs: [Object],
      seasons: 1,
      episodes: 6,
      age: 13,
      status: 4,
      tagline: '',
      streamingInfo: [Object],
      originalLanguage: 'en'
    },
    {
      imdbID: 'tt0106145',
      tmdbID: '580',
      imdbRating: 81,
      imdbVoteCount: 62757,
      tmdbRating: 78,
      backdropPath: '/jB3Ksk1tvhksdTa0xvI7l4LFHsy.jpg',
      backdropURLs: [Object],
      originalTitle: 'Star Trek: Deep Space Nine',
      genres: [Array],
      countries: [Array],
      year: 1993,
      firstAirYear: 1993,
      lastAirYear: 1999,
      episodeRuntimes: [Array],
      cast: [Array],
      significants: [Array],
      title: 'Star Trek: Deep Space Nine',
      overview: 'At Deep Space Nine, a space station located next to a wormhole in the vicinity of the liberated planet of Bajor, Commander Sisko and crew welcome alien visitors, root out evildoers and solve all types of unexpected problems that come their way.',
      video: 'cwNFUgYWGG4',
      posterPath: '/37gPCTyiQOLa9vJeKrpX4HqRq6P.jpg',
      posterURLs: [Object],
      seasons: 7,
      episodes: 176,
      age: 11,
      status: 4,
      tagline: '',
      streamingInfo: [Object],
      originalLanguage: 'en'
    },
    {
      imdbID: 'tt10574236',
      tmdbID: '90972',
      imdbRating: 76,
      imdbVoteCount: 24754,
      tmdbRating: 69,
      backdropPath: '/kiiPOuzjyIe793tgGsM5j5DaRxb.jpg',
      backdropURLs: [Object],
      originalTitle: 'Station Eleven',
      genres: [Array],
      countries: [Array],
      year: 2021,
      firstAirYear: 2021,
      lastAirYear: 2022,
      episodeRuntimes: [Array],
      cast: [Array],
      significants: [Array],
      title: 'Station Eleven',
      overview: "A post apocalyptic saga spanning multiple timelines telling the stories of survivors of a devastating flu as they attempt to rebuild and reimagine the world anew while holding on to the best of what's been lost.",
      video: 'LPm52rq8CZA',
      posterPath: '/xWlhMOzRxUpu4uzkWcDQOaESCE.jpg',
      posterURLs: [Object],
      seasons: 1,
      episodes: 10,
      age: 17,
      status: 4,
      tagline: '',
      streamingInfo: [Object],
      originalLanguage: 'en'
    }
  ],
  total_pages: 1
}
GET /show?country=ca&service=crave&type=series&keyword=station&page=1&output_language=en&language=en 304 - - 243.380 ms
{
  results: [
    {
      imdbID: 'tt15407098',
      tmdbID: '157282',
      imdbRating: 70,
      imdbVoteCount: 1566,
      tmdbRating: 70,
      backdropPath: '/o15mg5xbGkSPfW4e8ES42WzpZAy.jpg',
      backdropURLs: [Object],
      originalTitle: 'Sister Boniface Mysteries',
      genres: [Array],
      countries: [Array],
      year: 2022,
      firstAirYear: 2022,
      lastAirYear: 2022,
      episodeRuntimes: [Array],
      cast: [Array],
      significants: [Array],
      title: 'Sister Boniface Mysteries',
      overview: "First there was Father Brown. Now, say hello to Sister Boniface. This clever, moped-riding nun is the police's secret weapon for solving murders in this divine Father Brown spin-off.",     
      video: '8cIerKb_I8c',
      posterPath: '/leaPXZKi7OBKfLUwyoGu5bP5WU2.jpg',
      posterURLs: [Object],
      seasons: 1,
      episodes: 10,
      age: 11,
      status: 1,
      tagline: '',
      streamingInfo: [Object],
      originalLanguage: 'en'
    }
  ],
  total_pages: 1
}
GET /show?country=au&service=britbox&type=series&keyword=hello&page=1&output_language=en&language=en 304 - - 236.004 ms
{
  country: 'ca',
  service: 'crave',
  type: 'series',
  keyword: 'station',
  page: '1',
  output_language: 'en',
  language: 'en'
}
{
  country: 'au',
  service: 'britbox',
  type: 'series',
  keyword: 'hello',
  page: '1',
  output_language: 'en',
  language: 'en'
}
{
  results: [
    {
      imdbID: 'tt15407098',
      tmdbID: '157282',
      imdbRating: 70,
      imdbVoteCount: 1566,
      tmdbRating: 70,
      backdropPath: '/o15mg5xbGkSPfW4e8ES42WzpZAy.jpg',
      backdropURLs: [Object],
      originalTitle: 'Sister Boniface Mysteries',
      genres: [Array],
      countries: [Array],
      year: 2022,
      firstAirYear: 2022,
      lastAirYear: 2022,
      episodeRuntimes: [Array],
      cast: [Array],
      significants: [Array],
      title: 'Sister Boniface Mysteries',
      overview: "First there was Father Brown. Now, say hello to Sister Boniface. This clever, moped-riding nun is the police's secret weapon for solving murders in this divine Father Brown spin-off.",     
      video: '8cIerKb_I8c',
      posterPath: '/leaPXZKi7OBKfLUwyoGu5bP5WU2.jpg',
      posterURLs: [Object],
      seasons: 1,
      episodes: 10,
      age: 11,
      status: 1,
      tagline: '',
      streamingInfo: [Object],
      originalLanguage: 'en'
    }
  ],
  total_pages: 1
}
GET /show?country=au&service=britbox&type=series&keyword=hello&page=1&output_language=en&language=en 304 - - 205.912 ms
{
  results: [
    {
      imdbID: 'tt0397138',
      tmdbID: '429',
      imdbRating: 83,
      imdbVoteCount: 7434,
      tmdbRating: 81,
      backdropPath: '/uFyPlkJphA4MUIwjB1GE3wUH8SE.jpg',
      backdropURLs: [Object],
      originalTitle: 'Corner Gas',
      genres: [Array],
      countries: [Array],
      year: 2004,
      firstAirYear: 2004,
      lastAirYear: 2009,
      episodeRuntimes: [Array],
      cast: [Array],
      significants: [Array],
      title: 'Corner Gas',
      overview: 'Following the adventures of a bunch of nobodies who get up to a whole lot of nothing in the fictional prairie town of Dog River, Saskatchewan, Corner Gas focuses on the life (or lack thereof) of Brent LeRoy, proprietor of a gas station that is the only stop for miles around and a hub of action on the Prairies.',
      video: '',
      posterPath: '/2auwYcyedZ9GwrwRcVMijIPMO0T.jpg',
      posterURLs: [Object],
      seasons: 6,
      episodes: 108,
      age: 6,
      status: 4,
      tagline: '',
      streamingInfo: [Object],
      originalLanguage: 'en'
    },
    {
      imdbID: 'tt14903810',
      tmdbID: '128966',
      imdbRating: 66,
      imdbVoteCount: 259,
      tmdbRating: 65,
      backdropPath: '/eQqmPz78gt69MutwBAQTJbuRLms.jpg',
      backdropURLs: [Object],
      originalTitle: 'Small Town News: KPVM Pahrump',
      genres: [Array],
      countries: [Array],
      year: 2021,
      firstAirYear: 2021,
      lastAirYear: 2021,
      episodeRuntimes: [Array],
      cast: [Array],
      significants: [],
      title: 'Small Town News: KPVM Pahrump',
      overview: 'Pulling back the curtain on life at a privately owned TV station in the small desert town of Pahrump, Nevada, revealing a colorful cast of characters in front of and behind the cameras.',  
      video: 'sfu30G4AkJA',
      posterPath: '/zTRkIOK0x15WA9zeaxyKBwEZPM3.jpg',
      posterURLs: [Object],
      seasons: 1,
      episodes: 6,
      age: 13,
      status: 4,
      tagline: '',
      streamingInfo: [Object],
      originalLanguage: 'en'
    },
    {
      imdbID: 'tt0106145',
      tmdbID: '580',
      imdbRating: 81,
      imdbVoteCount: 62757,
      tmdbRating: 78,
      backdropPath: '/jB3Ksk1tvhksdTa0xvI7l4LFHsy.jpg',
      backdropURLs: [Object],
      originalTitle: 'Star Trek: Deep Space Nine',
      genres: [Array],
      countries: [Array],
      year: 1993,
      firstAirYear: 1993,
      lastAirYear: 1999,
      episodeRuntimes: [Array],
      cast: [Array],
      significants: [Array],
      title: 'Star Trek: Deep Space Nine',
      overview: 'At Deep Space Nine, a space station located next to a wormhole in the vicinity of the liberated planet of Bajor, Commander Sisko and crew welcome alien visitors, root out evildoers and solve all types of unexpected problems that come their way.',
      video: 'cwNFUgYWGG4',
      posterPath: '/37gPCTyiQOLa9vJeKrpX4HqRq6P.jpg',
      posterURLs: [Object],
      seasons: 7,
      episodes: 176,
      age: 11,
      status: 4,
      tagline: '',
      streamingInfo: [Object],
      originalLanguage: 'en'
    },
    {
      imdbID: 'tt10574236',
      tmdbID: '90972',
      imdbRating: 76,
      imdbVoteCount: 24754,
      tmdbRating: 69,
      backdropPath: '/kiiPOuzjyIe793tgGsM5j5DaRxb.jpg',
      backdropURLs: [Object],
      originalTitle: 'Station Eleven',
      genres: [Array],
      countries: [Array],
      year: 2021,
      firstAirYear: 2021,
      lastAirYear: 2022,
      episodeRuntimes: [Array],
      cast: [Array],
      significants: [Array],
      title: 'Station Eleven',
      overview: "A post apocalyptic saga spanning multiple timelines telling the stories of survivors of a devastating flu as they attempt to rebuild and reimagine the world anew while holding on to the best of what's been lost.",
      video: 'LPm52rq8CZA',
      posterPath: '/xWlhMOzRxUpu4uzkWcDQOaESCE.jpg',
      posterURLs: [Object],
      seasons: 1,
      episodes: 10,
      age: 17,
      status: 4,
      tagline: '',
      streamingInfo: [Object],
      originalLanguage: 'en'
    }
  ],
  total_pages: 1