export const COUNTRIES = [
    {country:'Argentina',code: 'ar'},
    {country:'Australia',code: 'au'},
    {country:'Austria',code: 'at'},
    {country:'Azerbaijan',code: 'az'},
    {country:'Belgium',code: 'be'},
    {country:'Brazil',code: 'br'},
    {country:'Bulgaria',code: 'bg'},
    {country:'Canada',code: 'ca'},
    {country:'Chile',code: 'cl'},
    {country:'Colombia',code: 'co'},
    {country:'Croatia',code: 'hr'},
    {country:'Cyprus',code: 'cy'},
    {country:'Czech Republic',code: 'cz'},
    {country:'Denmark',code: 'dk'},
    {country:'Ecuador',code: 'ec'},
    {country:'Estonia',code: 'ee'},
    {country:'Finland',code: 'fi'},
    {country:'France',code: 'fr'},
    {country:'Germany',code: 'de'},
    {country:'Greece',code: 'gr'},
    {country:'Hong Kong',code: 'hk'},
    {country:'Hungary',code: 'hu'},
    {country:'Iceland',code: 'il'},
    {country:'India',code: 'in'},
    {country:'Indonesia',code: 'id'},
    {country:'Ireland',code: 'ie'},
    {country:'Israel',code: 'is'},
    {country:'Italy',code: 'it'},
    {country:'Japan',code: 'jp'},
    {country:'Latvia',code: 'lv'},
    {country:'Lithuania',code: 'lt'},
    {country:'Malaysia',code: 'my'},
    {country:'Mexico',code: 'mx'},
    {country:'Moldova',code: 'md'},
    {country:'Netherlands',code: 'nl'},
    {country:'New Zealand',code: 'nz'},
    {country:'North Macedonia',code: 'mk'},
    {country:'Norway',code: 'no'},
    {country:'Panama',code: 'pa'},
    {country:'Peru',code: 'pe'},
    {country:'Philippines',code: 'ph'},
    {country:'Poland',code: 'pl'},
    {country:'Portugal',code: 'pt'},
    {country:'Romania',code: 'ro'},
    {country:'Russia',code: 'ru'},
    {country:'Serbia',code: 'rs'},
    {country:'Singapore',code: 'sg'},
    {country:'South Africa',code: 'za'},
    {country:'South Korea',code: 'sk'},
    {country:'Spain',code: 'es'},
    {country:'Sweden',code: 'se'},
    {country:'Switzerland',code: 'ch'},
    {country:'Thailand',code: 'th'},
    {country:'Tunisia',code: 'tn'},
    {country:'Turkey',code: 'tr'},
    {country:'Ukraine',code: 'ua'},
    {country:'United Emirates',code: 'ae'},
    {country:'United Kingdom',code: 'gb'},
    {country:'United States',code: 'us'},
    {country:'Vietnam',code: 'vn'}
    ]


export const SERVICES = [
    {"all4": [
        "gb",
        "ie"
    ]},
    {"apple": [
        "ie",
        "es",
        "nl",
        "gb",
        "pl",
        "ch",
        "dk",
        "se",
        "no",
        "it",
        "md",
        "in",
        "cz",
        "gr",
        "ua",
        "ca",
        "pt",
        "mx",
        "ru",
        "bg",
        "cy",
        "fi",
        "be",
        "ae",
        "at",
        "ee",
        "th",
        "de",
        "az",
        "fr",
        "br",
        "vn",
        "sg",
        "us",
        "jp",
        "il",
        "hk",
        "za",
        "pa",
        "au",
        "ph",
        "cl",
        "ar",
        "nz",
        "ec",
        "co",
        "hu",
        "id",
        "kr",
        "lt",
        "my",
        "pe"
    ]},
    {"britbox": [
        "gb",
        "us",
        "ca",
        "au",
        "za"
    ]},
    {"crave": [
        "ca"
    ]},
    {"curiosity": [
        "gb",
        "de",
        "dk",
        "be",
        "es",
        "ch",
        "cz",
        "ee",
        "ro",
        "rs",
        "it",
        "no",
        "ie",
        "pt",
        "pl",
        "hr",
        "at",
        "ru",
        "us",
        "tr",
        "ua",
        "gr",
        "bg",
        "fi",
        "mk",
        "th",
        "nl",
        "cy",
        "ca",
        "fr",
        "il",
        "is",
        "hk",
        "vn",
        "jp",
        "az",
        "mx",
        "in",
        "nz",
        "ae",
        "za",
        "br",
        "se",
        "au",
        "ph",
        "cl",
        "pa",
        "ar",
        "sg",
        "ec",
        "co",
        "hu",
        "id",
        "kr",
        "lt",
        "my",
        "pe"
    ]},
{    "disney": [
        "ca",
        "gb",
        "us",
        "nl",
        "au",
        "nz",
        "at",
        "de",
        "it",
        "es",
        "ch",
        "fr",
        "be",
        "dk",
        "fi",
        "no",
        "pt",
        "se",
        "ar",
        "br",
        "cl",
        "co",
        "mx",
        "ie",
        "jp",
        "id",
        "is",
        "ec",
        "pa",
        "pe",
        "sg",
        "my",
        "th",
        "kr",
        "hk",
        "za",
        "tr"
    ]},
{    "hbo": [
        "nl",
        "us",
        "ar",
        "br",
        "cl",
        "co",
        "ec",
        "mx",
        "pe",
        "dk",
        "fi",
        "no",
        "es",
        "se",
        "bg",
        "hr",
        "cz",
        "hu",
        "md",
        "mk",
        "pl",
        "pt",
        "ro",
        "rs"
    ]},
{    "hotstar": [
        "in",
        "ca",
        "gb",
        "id",
        "sg"
    ]},
{    "hulu": [
        "us"
    ]},
{    "iplayer": [
        "gb"
    ]},
{    "mubi": [
        "ch",
        "il",
        "ru",
        "be",
        "es",
        "at",
        "mk",
        "pl",
        "md",
        "ua",
        "rs",
        "se",
        "jp",
        "ee",
        "ca",
        "cy",
        "ro",
        "bg",
        "dk",
        "fi",
        "nl",
        "fr",
        "az",
        "gb",
        "no",
        "gr",
        "de",
        "hk",
        "us",
        "it",
        "ae",
        "sg",
        "ie",
        "vn",
        "pa",
        "za",
        "cl",
        "au",
        "nz",
        "tr",
        "ar",
        "th",
        "in",
        "br",
        "ph",
        "mx",
        "hr",
        "ec",
        "co",
        "hu",
        "id",
        "kr",
        "lt",
        "my",
        "pe"
    ]},
{    "netflix": [
        "ar",
        "at",
        "au",
        "be",
        "br",
        "ca",
        "ch",
        "cl",
        "co",
        "cz",
        "de",
        "dk",
        "ec",
        "ee",
        "es",
        "fi",
        "fr",
        "gb",
        "gr",
        "hu",
        "id",
        "ie",
        "in",
        "it",
        "jp",
        "kr",
        "lt",
        "mx",
        "my",
        "nl",
        "no",
        "nz",
        "pe",
        "ph",
        "pl",
        "pt",
        "ro",
        "se",
        "sg",
        "th",
        "tr",
        "us",
        "za",
        "hr",
        "az",
        "bg",
        "cy",
        "hk",
        "is",
        "il",
        "md",
        "mk",
        "rs",
        "ua",
        "ae",
        "vn",
        "pa"
    ]},
{    "now": [
        "gb",
        "ie",
        "it"
    ]},
{    "paramount": [
        "us"
    ]},
{    "peacock": [
        "us"
    ]},
{    "prime": [
        "jp",
        "nl",
        "nz",
        "se",
        "il",
        "dk",
        "th",
        "ec",
        "cl",
        "ee",
        "cz",
        "de",
        "no",
        "ru",
        "md",
        "ph",
        "co",
        "rs",
        "id",
        "pe",
        "za",
        "fr",
        "in",
        "hk",
        "pa",
        "kr",
        "ro",
        "hr",
        "at",
        "ca",
        "ar",
        "ie",
        "us",
        "hu",
        "br",
        "it",
        "mx",
        "pl",
        "sg",
        "ch",
        "cy",
        "lt",
        "my",
        "is",
        "es",
        "ae",
        "az",
        "bg",
        "pt",
        "au",
        "fi",
        "tr",
        "be",
        "gr",
        "gb",
        "ua",
        "mk",
        "vn"
    ]},
{    "showtime": [
        "us"
    ]},
{    "stan": [
        "au"
    ]},
{    "starz": [
        "us"
    ]},
{    "zee5": [
        "gb",
        "de",
        "dk",
        "be",
        "es",
        "ch",
        "cz",
        "ee",
        "ro",
        "rs",
        "it",
        "no",
        "ie",
        "pt",
        "pl",
        "hr",
        "at",
        "ru",
        "us",
        "tr",
        "ua",
        "gr",
        "bg",
        "fi",
        "mk",
        "th",
        "nl",
        "cy",
        "md",
        "ca",
        "fr",
        "il",
        "is",
        "hk",
        "vn",
        "jp",
        "az",
        "mx",
        "in",
        "nz",
        "ae",
        "za",
        "br",
        "se",
        "au",
        "ph",
        "cl",
        "pa",
        "ar",
        "sg",
        "ec",
        "co",
        "hu",
        "id",
        "kr",
        "lt",
        "my",
        "pe"
    ]
 }
]